#!/bin/bash
##
## Before running you should backup your settings:
##
## 1. File -> Export settings
## 2. close IDE

set -e

BACKUP=~/backup/$(date --iso-8601)

IDEA=~/.IntelliJIdea2018.1

if [[ ! -d $IDEA ]]; then
  echo "Error: Expected IDEA folder not found: $IDEA"
  echo "Are you using a different IDEA version?"
  exit 1
fi

if [[ -d $BACKUP ]]; then
  echo "Error: Backup folder exists: $BACKUP"
  exit 1
fi

set -x
mkdir -p $BACKUP
set +x

## Remove prefs.xml
mv ~/.java/.userPrefs/prefs.xml $BACKUP

## ..but retain lines that don't contain the word JetBrains
grep -F -v JetBrains $BACKUP/prefs.xml >~/.java/.userPrefs/prefs.xml

## Remove jetbrains preferences folder
mv ~/.java/.userPrefs/jetbrains/ $BACKUP

## Remove idea folder
mv $IDEA $BACKUP
