#!/bin/bash

set -e


function ask() {
  read CONFIRMATION
  if [[ -n "$CONFIRMATION" ]] && [[ "$CONFIRMATION" != "y" ]] && [[ "$CONFIRMATION" != "Y" ]]; then
    echo "quitting now"
    exit 0
  fi
}

function find_idea_folder() {
    find -L $HOME -mindepth 1 -maxdepth 1 -xtype d | grep -F IntelliJIdea
    find -L ${HOME}/.config/JetBrains/ -mindepth 1 -maxdepth 1 -xtype d | grep -F IntelliJIdea
}

function show_idea_folder_options() {
    for F in $(find_idea_folder); do
        if [[ "$F" == "$IDEA" ]]; then
            echo "* $F"
        else
            echo "  $F"
        fi
    done
}

while getopts "d:" OPTION; do
    case $OPTION in
    d)
	if [[ ! -d "$OPTARG" ]]; then
		echo "Invalid IDEA folder specified: Not a directory"
		exit 1
	fi
        IDEA=$OPTARG
        ;;
    *)
        echo "Incorrect options provided"
        exit 1
        ;;
    esac
done

if [[ -z ${IDEA} ]] || [[ ! -d "${IDEA}" ]]; then
  echo "IDEA folder not specified."
  echo "You must specify the full path of this folder with the -d option."
  echo "Possible values are:"
  show_idea_folder_options
  exit 1
fi

echo "Using IDEA folder ${IDEA}."
echo "Listing all possible values for the -d option:"
echo "---------------------------------"
show_idea_folder_options
echo "---------------------------------"
echo "If you disagree, you can quit now and start over,"
echo "and specify a different folder with the -d option."
echo "Continue? [n|Y]"
ask

BACKUP="$HOME/backup/$(date --iso-8601)"

function ask() {
  read CONFIRMATION
  if [[ -n "$CONFIRMATION" ]] && [[ "$CONFIRMATION" != "y" ]] && [[ "$CONFIRMATION" != "Y" ]]; then
    echo "quitting now"
    exit 0
  fi
}

if [[ -d "$BACKUP" ]]; then
  echo "Error: Backup folder exists: $BACKUP"
  exit 1
fi

echo "Using IDEA folder: $IDEA"
echo
echo "Please make sure to backup your IDEA settings!"
echo "(File -> Export settings)"
echo "Please be sure to store a copy of settings.zip outside of $IDEA."
echo
echo "Your settings will be lost if you don't have a backup."
echo "Please be sure that IDEA is not running before you proceed."
echo "Continue? [n|Y]"
ask

echo "Creating backup in $BACKUP"
mkdir -p $BACKUP

set -x

## Remove prefs.xml
if [[ -f "$HOME/.java/.userPrefs/prefs.xml" ]]; then
  mv "$HOME/.java/.userPrefs/prefs.xml" $BACKUP
  ## ..but keep lines that don't contain the word JetBrains
  grep -F -v JetBrains $BACKUP/prefs.xml >$HOME/.java/.userPrefs/prefs.xml
fi

## Remove jetbrains preferences folder
if [[ -d "$HOME/.java/.userPrefs/jetbrains" ]]; then
  mv "$HOME/.java/.userPrefs/jetbrains" $BACKUP
fi

## Remove idea folder
mv $IDEA $BACKUP
set +x

echo "Refresh is done."
echo "It is recommended to download a fresh idea release now."
