#!/bin/bash

set -e

addLine () {
	echo -n "PADDING " >>"$1"
	openssl rand -base64 23 >>"$1"
}

CLOBBER=N

if [[ "-x" == "$1" ]] || [[ "--clobber" == "$1" ]]; then
  CLOBBER=Y
  shift
fi

FILE="$1"
HEAD=HEAD
OUT=OUT

cp "$FILE" "${FILE}_${OUT}"
for i in `seq 100`; do
	addLine "${FILE}_${HEAD}"
	addLine "${FILE}_${OUT}"
done

cat "${FILE}_${OUT}" >>"${FILE}_${HEAD}"
mv --backup=numbered "${FILE}_${HEAD}" "${FILE}_${OUT}" 

if [[ "Y" == "$CLOBBER" ]]; then
  mv --backup=numbered "${FILE}_${OUT}" "$FILE"
  echo "$FILE was modified"
else
  echo "${FILE}_${OUT} created"
fi

