#!/bin/bash

addLine () {
	echo -n "PADDING " >>"$1"
	openssl rand -base64 23 >>"$1"
}

FILE="$1"
HEAD=HEAD
OUT=OUT

cp "$FILE" "${FILE}_${OUT}"
for i in `seq 100`; do
	addLine "${FILE}_${HEAD}"
	addLine "${FILE}_${OUT}"
done

cat "${FILE}_${OUT}" >>"${FILE}_${HEAD}"
mv --backup=numbered "${FILE}_${HEAD}" "${FILE}_${OUT}" 

if [[ "--replace" == "$2" ]]; then
  mv --backup=numbered "${FILE}_${OUT}" "$FILE"
  echo "$FILE was modified"
else
  echo "${FILE}_${OUT} created"
fi

