#!/bin/bash

# example: press_down "one two three"
press_down() {
  local mychar mode val values i clr pos=0
  for val in $1; do
    values+=($val)
  done
  clr="\r"
  for i in "${!values[@]}"; do
    clr="$clr\033[A\033[K"
  done
  while :; do
    for i in "${!values[@]}"; do
      if (( i == pos )); then
        1>&2 echo "${values[i]} <-"
      else
        1>&2 echo "${values[i]}"
      fi
    done
    read -rsN1 mychar
    read -t0.01 -rsN2 mode
    if [[ $mychar = $'\12' ]]; then
      break
    fi
    if [[ $mychar = $'\33' && -z $mode ]]; then
      break
    fi
    if [[ $mychar = "j" || $mode == "[B" ]]; then
      (( pos++ ))
    elif [[  $mychar = "k" || $mode == "[A" ]]; then
      (( pos-- ))
    fi
    (( pos < 0 && ( pos += ${#values[@]} ) ))
    (( pos = ( pos % ${#values[@]} ) ))
    1>&2 printf "$clr"
  done
}

return 2> /dev/null || {
  press_down "$@"
}
