#!/bin/bash
set -e

[[ $EUID = "0" ]] && {
  echo "ERROR do not run this as root"
  exit 1
}

[[ $(mount | grep -q -F /mnt/ramdisk) ]] && {
  mount | grep -F /mnt/ramdisk
  exit 0
}

[[ -d /mnt/ramdisk ]] || {
  sudo mkdir /mnt/ramdisk
}

sudo mount -t ramfs -o size=64M ramfs /mnt/ramdisk
sudo chown -R $USER: /mnt/ramdisk/
