#!/bin/bash
set -e

if [[ "0" == `id -u` ]]; then
  echo "ERROR do not run this as root"
  exit 1
fi

if [[ ! -z `mount | fgrep /mnt/ramdisk` ]]; then
  mount | fgrep /mnt/ramdisk
  exit 	
fi

if [[ ! -d /mnt/ramdisk ]]; then
  sudo mkdir /mnt/ramdisk
fi

sudo mount -t ramfs -o size=64M ramfs /mnt/ramdisk
OLD_USER=$USER
sudo chown -R ${OLD_USER}: /mnt/ramdisk/
mount | fgrep /mnt/ramdisk

