#!/bin/bash
set -e

DIR="VID-$(date --iso-8601)"

if [[ ! -e $DIR ]]; then
	mkdir $DIR
fi

cd $DIR
YELLOW='\033[1;33m'
NC='\033[0m'
echo -e "${YELLOW}Saving screencast to $(pwd)/output.mkv${NC}"

RES=$(xdpyinfo | grep -oP 'dimensions:\s+\K\S+')
yes | ffmpeg -video_size 1920x1080 -framerate 30 -f x11grab -i :0.0 -c:v libx264rgb -crf 0 -preset ultrafast output.mkv

