#!/bin/bash

# $1: device
# $2: size, example: 256G
shrink_lvm() {
  [[ -n $1 && -n $2 ]] || return
  e2fsck $1 || return
  lvreduce --resizefs --size $2 $1
}

return 2> /dev/null || {
  shrink_lvm "$@"
}
