#!/bin/bash

set -e

FILE="$1"
OUT=OUT

grep -E -v ^PADDING  "$FILE" >"${FILE}_${OUT}"

N1=`wc -l "$FILE" | cut -d" " -f1`
N2=`wc -l "${FILE}_${OUT}" | cut -d" " -f1`
DIFF=$(( N1 - N2 ))

echo "$DIFF lines removed"

mv --backup=numbered "${FILE}_${OUT}" "$FILE"
echo "$FILE was modified"
