#!/bin/bash

set -e

FILE="$1"
OUT=OUT

grep -E -v ^PADDING  "$FILE" >"${FILE}_${OUT}"

N1=`wc -l "$FILE" | cut -d" " -f1`
N2=`wc -l "${FILE}_${OUT}" | cut -d" " -f1`
DIFF=$(( N1 - N2 ))

if [[ $DIFF != "200" ]]; then
  echo "Diff fail!"
  exit 1
fi

mv --backup=numbered "${FILE}_${OUT}" "$FILE"
echo "$FILE was changed"
