#!/bin/bash

remove_tab () {
  sed -i -E "s/^([ ]*)\t/\1  /" $1
}

if [[ -z $1 ]]; then
  echo "Parameter: file or directory"
  exit 1
 fi

for i in $(seq 1 8); do
  if [[ -f $1 ]]; then
    remove_tab $1
  elif [[ -d $1 ]]; then
  	for S in $(find $1 -type f); do
  		remove_tab $S
  	done
  else
    echo "error"
  fi
done
