#!/bin/bash

assume_yes=false
read_command="read -p"

target_release() {
  local arch=$(uname -m)
  curl -s "https://fedoraproject.org/releases.json" | jq -r ".[]|select(.arch==\"$arch\")|.version" | sort -rn | head -1
}

is_update_prepared() {
  dnf offline status | grep -F -q "offline reboot"
}

check_updates_available() {
  dnf check-update
  local n=$(dnf updateinfo summary 2>&1 | sed -n -E 's/.*([0-9]+)$/\1/p' | paste -sd+ | bc)
  (( n > 0 ))
}

current_release() {
  sed -n -E 's/^VERSION_ID=(\S+)/\1/p' /etc/os-release
}

system_update() {
  local target=$1
  local REPLY
  dnf -y system-upgrade download --releasever=$target && {
    $read_command "The system update is prepared. Would you like to reboot right now? [y/N] "
    if $assume_yes || [[ $REPLY =~ [yY] ]]; then dnf -y offline reboot; fi
  }
}

normal_update() {
  local REPLY
  dnf -y update --refresh --offline && {
    $read_command "The update is prepared. Would you like to reboot right now? [y/N] "
    if $assume_yes || [[ $REPLY =~ [yY] ]]; then dnf -y offline reboot; fi
  }
}

default_action() {
  local REPLY
  is_update_prepared && {
    $read_command "An update is prepared. Would you like to reboot right now? [y/N] "
    if $assume_yes || [[ $REPLY =~ [yY] ]]; then dnf -y offline reboot; fi
    return 0
  }
  check_updates_available && {
    $read_command "An update ist available. Would you like to download it now? [y/N] "
    if $assume_yes || [[ $REPLY =~ [yY] ]]; then normal_update; fi
    return 0
  }
  local current=$(current_release)
  local target=$(target_release)
  if (( current == target )); then
    echo "The system is up-to-date."
  elif (( target - current == 1 )); then
    $read_command "A system update to fedora $target is available. Would you like to download it now? [y/N] "
    if $assume_yes || [[ $REPLY =~ [yY] ]]; then system_update $target; fi
    return 0
  else
    echo "The system is too far behind. Please update manually."
  fi
}

return 2> /dev/null || {
  [[ $EUID = "0" ]] || {
    echo "run as root"
    exit 1
  }
  [[ $1 = "-y" ]] && {
    assume_yes=true
    read_command=echo
  }
  default_action
}
