#!/bin/bash

assume_yes=false

read_yes() {
  echo "$@"
  echo "y"
  REPLY=y
}

release_type() {
  sed -n -E 's/^RELEASE_TYPE=(\S+)/\1/p' /etc/os-release
}

os_release() {
  sed -n -E 's/^VERSION_ID=(\S+)/\1/p' /etc/os-release
}

target_release() {
  local result
  local current=$(os_release)
  if [[ $(release_type) != "stable" ]]; then
    echo $current
    return 0
  fi
  local metainfo=/usr/share/metainfo/org.fedoraproject.fedora.metainfo.xml
  if [[ -f $metainfo ]]; then
    result=$(xmllint --xpath "/component/releases//release[@type='stable']/@version" $metainfo | \
      sed -n -E 's/.*[=]["]([0-9]+)["].*/\1/p' | \
      sort -rn | \
      head -1)
  else
    result=$(curl -s "https://fedoraproject.org/releases.json" | \
      jq -r ".[]|select( .arch == \"$(uname -m)\") |.version" | \
      sort -rn | \
      head -1)
  fi
  if (( result >= current )); then
    echo $result
  else
    echo $current
  fi
}

update_show() {
  sudo dnf check-update --refresh
}

is_update_prepared() {
  sudo dnf offline status | grep -F -q "offline reboot"
}

check_updates_available() {
  [[ $(update_show 2> /dev/null) ]]
}

system_update() {
  local target=$1
  sudo dnf -y system-upgrade download --releasever=$target && {
    $read_p "A system update is prepared. Would you like to reboot right now? [y/N] "
    [[ $REPLY =~ [yY] ]] && sudo dnf -y offline reboot
  }
}

update_apply() {
  sudo dnf -y update --refresh
}

update_download() {
  sudo dnf -y update --refresh --offline && {
    $read_p "An update is prepared. Would you like to reboot right now? [y/N] "
    [[ $REPLY =~ [yY] ]] && sudo dnf -y offline reboot
  }
}

default_action() {
  read_p="read -p"
  [[ $1 = "-y" ]] && {
    read_p=read_yes
    assume_yes=true
  }
  is_update_prepared && {
    $read_p "An update is prepared. Would you like to reboot right now? [y/N] "
    [[ $REPLY =~ [yY] ]] && sudo dnf -y offline reboot
    return 0
  }
  check_updates_available && {
    while true; do
      $read_p "An update is available. [s]how [d]ownload [a]pply [q]uit [h]elp ? "
      case $REPLY in
        s)
          update_show
          ;;
        d)
          update_download
          return 0
          ;;
        a)
          update_apply
          return 0
          ;;
        q)
          return 0
          ;;
        *)
          echo "s = show available updates"
          echo "d = download updates for offline update"
          echo "a = apply updates (no reboot)"
          echo "q = quit"
          echo "h = show help"
          ;;
      esac
    done
  }
  local current=$(os_release)
  local target=$(target_release)
  if (( current == target )); then
    echo "The system is up-to-date."
    if ! $assume_yes && [[ $(release_type) = "stable" ]]; then
      read -p "Would you like to upgrade to rawhide? [y/N] "
      [[ $REPLY =~ [yY] ]] && system_update rawhide
    fi
  else
    $read_p "A system update to fedora $(( current + 1 )) is available. Would you like to download it now? [y/N] "
    [[ $REPLY =~ [yY] ]] && system_update $(( current + 1 ))
  fi
  return 0
}

return 2> /dev/null || {
  default_action $@
}
