alias cd-='cd -'
alias ll='ls --color=auto -lart'
alias clear='clear && reset'
alias reset='clear && reset'
alias pwd='pwd -P'
alias ack='ack -Q'
alias pull='git pull origin $(git rev-parse --abbrev-ref HEAD)'
alias push='git push origin $(git rev-parse --abbrev-ref HEAD)'
alias show='git show'
alias glg='git log'
alias br='git branch --sort=committerdate'
alias st='git status'
alias log1='git log -n1'
alias log2='git log -n2'
alias log3='git log -n3'
alias log4='git log -n4'
alias log5='git log -n5'
alias log6='git log -n6'
alias log7='git log -n7'
alias log8='git log -n8'
alias log9='git log -n9'
alias mkdir='mkdir -p'
alias sudo='sudo ' #man bash
alias videos='cd ~/Videos'
alias pictures='cd ~/Pictures'
alias downloads='cd ~/Downloads'
alias cherrypick='git cherry-pick'

