alias ll='ls --color=auto -Llart'
alias lll='ls -1'
alias pwd='pwd -P'
alias ack='ack -Q'
alias pull='git pull origin $(git rev-parse --abbrev-ref HEAD)'
alias push='git push origin $(git rev-parse --abbrev-ref HEAD)'
alias show='git show'
alias log='git log'
alias show='git show'
alias st='git status'
alias log1='git log -n1'
alias log2='git log -n2'
alias log3='git log -n3'
alias log4='git log -n4'
alias log5='git log -n5'
alias log6='git log -n6'
alias log7='git log -n7'
alias log8='git log -n8'
alias log9='git log -n9'
alias mkdir='mkdir -p'
alias cb='cp --backup=numbered'
alias sudo='sudo ' #man bash
alias cob='git co -b'
alias youtube-dl='cd ~/Videos/ && youtube-dl'
alias my-scripts='cd ~/workspace/my-scripts'
alias master='git co master'
alias git-shortlog='for S in `git shortlog -s | cut -f2`; do echo $S; done'
