alias ll="ls -lArt --color=auto"
alias push='git push origin $(git rev-parse --abbrev-ref HEAD)'
alias pull='git pull origin $(git rev-parse --abbrev-ref HEAD)'
alias st="git status"
alias br="git branch"
alias cherrypick="git cherry-pick"
alias log="git log"
alias log1="git log -n1"
alias log2="git log -n2"
alias log3="git log -n3"
alias log4="git log -n4"
alias log5="git log -n5"
alias log6="git log -n6"
alias log7="git log -n7"
alias log8="git log -n8"
alias log9="git log -n9"
