#!/bin/bash

if [[ -z $1 ]]; then
  echo "Argument: input file"
fi

filename=$(basename -- "$1")
extension="${filename##*.}"
newFilename="${filename%.*}_small.pdf"

gs \
  -sDEVICE=pdfwrite\
  -dCompatibilityLevel=1.4\
  -dPDFSETTINGS=/screen\
  -dNOPAUSE\
  -dQUIET\
  -dBATCH\
  -sOutputFile="$newFilename"\
  "$1"

echo "$newFilename"
