#!/bin/bash
# about:logging
# New log modules: nsHttp:3

ulimit -n 8240
source merge_chunks

dl_chunk() {
  curl "$1" \
    -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0' \
    -H 'Accept: */*' \
    -H 'Accept-Language: en-US,en;q=0.5' \
    -H 'Accept-Encoding: gzip, deflate, br' \
    -H 'Origin: https://player02.getcourse.ru' \
    -H 'Connection: keep-alive' \
    -H 'Referer: https://player02.getcourse.ru/' \
    -H 'Sec-Fetch-Dest: empty' \
    -H 'Sec-Fetch-Mode: cors' \
    -H 'Sec-Fetch-Site: cross-site' \
    -O
}

FILE=$1

if [[ -z $FILE ]]; then
  echo "Syntax: $0 FILE"
  echo "Example: $0 M01L03.txt"
  exit 1
fi

MODULE="${FILE%%.*}"
URLS=$(fgrep 'E/nsHttp uri=https://' $FILE | grep -E '\d+\.ts')

URLS_CLEAN=$(cut -f6 -d' ' $FILE | cut -c 5- | uniq)

rm -rf $MODULE
mkdir $MODULE
cd $MODULE

for S in ${URLS_CLEAN[@]}; do
  echo $S
  dl_chunk "$S"
  sleep 1
done

check_gaps
merge_chunks $MODULE

