#!/bin/bash

join_strings () { 
  local IFS="|"; 
  echo "$*"; 
}

merge_chunks () {
  declare -a local FILES
  local INDEX=0

  # https://github.com/jbock-java/modular-thermosiphon/tree/sort-by-filename
  for S in $(ls -1 *.ts | grep -E ^\\d | java -jar sort-by-filename.jar); do
    FILES[INDEX]=$S
    INDEX=$(( INDEX + 1 ))
  done

  local JOINED=$(join_strings ${FILES[@]})
  ffmpeg -y -i "concat:$JOINED" -c copy ${1}.mp4
}

