#!/bin/bash

join_strings () { 
  local IFS="|"; 
  echo "$*"; 
}

merge_chunks () {
  declare -a local FILES
  local INDEX=0

  for S in $(ls -1 *.ts | grep -E ^\\d | awk 'BEGIN {FS="."} {printf("%06d\t%s\n",$1,$0)}' | sort | cut -f2); do
    FILES[INDEX]=$S
    INDEX=$(( INDEX + 1 ))
  done

  local JOINED=$(join_strings ${FILES[@]})
  ffmpeg -y -i "concat:$JOINED" -c copy ${1}.mp4
}

